/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author kuson
 */
public class GenerateReport extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReport
     */
     DefaultTableModel model ;
    
    public GenerateReport() {
        initComponents();
        comboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        labelhome = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        labelrecord = new javax.swing.JPanel();
        btn_record = new javax.swing.JLabel();
        labelcourses = new javax.swing.JPanel();
        btn_courses = new javax.swing.JLabel();
        labellist = new javax.swing.JPanel();
        btn_home3 = new javax.swing.JLabel();
        labelallrecord = new javax.swing.JPanel();
        btn_home4 = new javax.swing.JLabel();
        labelback = new javax.swing.JPanel();
        btn_home5 = new javax.swing.JLabel();
        labellogout = new javax.swing.JPanel();
        btn_home6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_courseDetails = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateChooser_to = new com.toedter.calendar.JDateChooser();
        dateChooser_from = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_filePath = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_feesDetails = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbl_totalInWords = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        lbl_totalAmount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelhome.setBackground(new java.awt.Color(0, 102, 102));
        labelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelhomeMouseExited(evt);
            }
        });
        labelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btn_home.setText(" HOME");
        btn_home.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });
        labelhome.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 70));

        panelsidebar.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, 80));

        labelrecord.setBackground(new java.awt.Color(0, 102, 102));
        labelrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelrecordMouseExited(evt);
            }
        });
        labelrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_record.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btn_record.setText("Search Record");
        btn_record.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recordMouseClicked(evt);
            }
        });
        labelrecord.add(btn_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 70));

        panelsidebar.add(labelrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 80));

        labelcourses.setBackground(new java.awt.Color(0, 102, 102));
        labelcourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelcourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelcoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelcoursesMouseExited(evt);
            }
        });
        labelcourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_courses.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_courses.setForeground(new java.awt.Color(255, 255, 255));
        btn_courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_courses.setText(" Edit Courses");
        btn_courses.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coursesMouseClicked(evt);
            }
        });
        labelcourses.add(btn_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, -1));

        panelsidebar.add(labelcourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 300, 80));

        labellist.setBackground(new java.awt.Color(0, 102, 102));
        labellist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labellist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labellistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labellistMouseExited(evt);
            }
        });
        labellist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home3.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home3.setForeground(new java.awt.Color(255, 255, 255));
        btn_home3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btn_home3.setText(" Course List");
        btn_home3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labellist.add(btn_home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 60));

        panelsidebar.add(labellist, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 300, 80));

        labelallrecord.setBackground(new java.awt.Color(0, 102, 102));
        labelallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelallrecordMouseExited(evt);
            }
        });
        labelallrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home4.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home4.setForeground(new java.awt.Color(255, 255, 255));
        btn_home4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_home4.setText("View All Record");
        btn_home4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home4MouseClicked(evt);
            }
        });
        labelallrecord.add(btn_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        panelsidebar.add(labelallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 300, 80));

        labelback.setBackground(new java.awt.Color(0, 102, 102));
        labelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackMouseExited(evt);
            }
        });
        labelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home5.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home5.setForeground(new java.awt.Color(255, 255, 255));
        btn_home5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btn_home5.setText(" Back");
        btn_home5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home5MouseClicked(evt);
            }
        });
        labelback.add(btn_home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 70));

        panelsidebar.add(labelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 300, 80));

        labellogout.setBackground(new java.awt.Color(0, 102, 102));
        labellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labellogoutMouseExited(evt);
            }
        });
        labellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home6.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home6.setForeground(new java.awt.Color(255, 255, 255));
        btn_home6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_home6.setText(" Logout");
        btn_home6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home6MouseClicked(evt);
            }
        });
        labellogout.add(btn_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 70));

        panelsidebar.add(labellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 300, 80));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 810));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From Date :-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 30));

        combo_courseDetails.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel1.add(combo_courseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Course :-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Date :-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        dateChooser_to.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(dateChooser_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, 30));

        dateChooser_from.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(dateChooser_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 100, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Export To Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 160, 40));

        txt_filePath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filePathActionPerformed(evt);
            }
        });
        jPanel1.add(txt_filePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 40));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 40));

        tbl_feesDetails.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tbl_feesDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Receipt No", "Roll No", "Student Name", "Course ", "Total Amount"
            }
        ));
        tbl_feesDetails.setGridColor(new java.awt.Color(102, 102, 102));
        tbl_feesDetails.setRowHeight(35);
        tbl_feesDetails.setRowMargin(4);
        tbl_feesDetails.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tbl_feesDetails.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_feesDetails.setShowGrid(false);
        jScrollPane1.setViewportView(tbl_feesDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 960, 470));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_totalInWords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_totalInWords.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 430, 30));

        lbl_course.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 120, 30));

        lbl_totalAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_totalAmount.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course Selected :-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount Collected :-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Amount In Words :-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 450, 200));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To Date :-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1160, 810));

        setSize(new java.awt.Dimension(1554, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void comboBox()
    {
          try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/fees_management","root","");
            PreparedStatement stm = con.prepareStatement("SELECT CNAME FROM course");
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                String name  = rs.getString("CNAME");
                combo_courseDetails.addItem(name);
                
            }
          

        
        } 
        catch (Exception ex) {
           ex.printStackTrace();
           System.out.println(ex);
        }
    }
     
     public void setRecordsToTable()
    {
        String cname = combo_courseDetails.getSelectedItem().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
        String fromdate = dateformat.format(dateChooser_from.getDate());
        String todate = dateformat.format(dateChooser_to.getDate());
        Float totalamount = 00.0f;
        
        try
        {
              Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/fees_management","root","");
            PreparedStatement pst = con.prepareStatement( "select * from fees_Details where date between ? and ? and courses = ?");
            pst.setString(1, fromdate);
            pst.setString(2,todate);
            pst.setString(3, cname);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next())
            {
                String receiptno = rs.getString("reciept_no");
                String rollno = rs.getString("roll_no");
                String studentname =rs.getString("student_name");
                String coursename = rs.getString("courses");
                float amount = rs.getFloat("total_amount");
                
                totalamount = totalamount + amount;
                
                Object[] obj = {receiptno,rollno,studentname,coursename,amount};
               model = (DefaultTableModel)tbl_feesDetails.getModel();
               model.addRow(obj);
            }
            lbl_course.setText(cname);
            lbl_totalAmount.setText(totalamount.toString());
            lbl_totalInWords.setText(NumberToWordsConverter.convert(totalamount.intValue())+" only");
           
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
     
      public void clearTable()
    {
        DefaultTableModel model = (DefaultTableModel)tbl_feesDetails.getModel();
        model.setRowCount(1);
    }
      
      public void exportToExcel()
      {
          XSSFWorkbook wb  =new XSSFWorkbook();
          XSSFSheet ws = wb.createSheet();
           DefaultTableModel model = (DefaultTableModel)tbl_feesDetails.getModel();
          
          TreeMap<String ,Object[]> map = new TreeMap<>();
          
          map.put("0",new Object []{model.getColumnName(0),model.getColumnName(1),model.getColumnName(2),
              model.getColumnName(3),model.getColumnName(4)});
          
          for(int i = 1 ; i<model.getRowCount();i++)
          {
              map.put(Integer.toString(i),new Object[]{model.getValueAt(i, 0),model.getValueAt(i, 1),
                  model.getValueAt(i, 2), model.getValueAt(i, 3),model.getValueAt(i, 4)});
          }
          
          Set<String> id = map.keySet();
          
          XSSFRow fRow ;
          
          int rowId = 0;
          
          for( String key : id)
          {
              fRow = ws.createRow(rowId++);
              Object [] value = map.get(key);
              
              int cellId = 0;
              
              for( Object object : value)
              {
                  XSSFCell cell = fRow.createCell(cellId++);
                  cell.setCellValue(object.toString());
              }
          }
          try(FileOutputStream fos =  new FileOutputStream(new File(txt_filePath.getText()))){
              
          
          wb.write(fos);
          JOptionPane.showMessageDialog(this, "File Exported Successfully:"+txt_filePath.getText());
          
          }
          catch(Exception e)
          {
              e.printStackTrace();
          }
          
          
//         for(Map.Entry<String,Object[]>entry : map.entrySet()){
//             String key = entry.getKey();
//             Object[] value  = entry.getValue();
//             System.out.println(Arrays.toString(value));
//         }
                  
                  
      }
    
    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeMouseClicked

    private void labelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelhome.setBackground(clr);
    }//GEN-LAST:event_labelhomeMouseEntered

    private void labelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labelhome.setBackground(clr);
    }//GEN-LAST:event_labelhomeMouseExited

    private void btn_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recordMouseClicked
        // TODO add your handling code here:
        SearchRecord search= new SearchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_recordMouseClicked

    private void labelrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelrecordMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelrecord.setBackground(clr);
    }//GEN-LAST:event_labelrecordMouseEntered

    private void labelrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelrecordMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labelrecord.setBackground(clr);
    }//GEN-LAST:event_labelrecordMouseExited

    private void btn_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coursesMouseClicked
        // TODO add your handling code here:
        EditCourse edit = new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_coursesMouseClicked

    private void labelcoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcoursesMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelcourses.setBackground(clr);
    }//GEN-LAST:event_labelcoursesMouseEntered

    private void labelcoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcoursesMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labelcourses.setBackground(clr);
    }//GEN-LAST:event_labelcoursesMouseExited

    private void labellistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellistMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labellist.setBackground(clr);
    }//GEN-LAST:event_labellistMouseEntered

    private void labellistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellistMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labellist.setBackground(clr);
    }//GEN-LAST:event_labellistMouseExited

    private void labelallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelallrecordMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelallrecord.setBackground(clr);
    }//GEN-LAST:event_labelallrecordMouseEntered

    private void labelallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelallrecordMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labelallrecord.setBackground(clr);
    }//GEN-LAST:event_labelallrecordMouseExited

    private void labelbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelback.setBackground(clr);
    }//GEN-LAST:event_labelbackMouseEntered

    private void labelbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labelback.setBackground(clr);
    }//GEN-LAST:event_labelbackMouseExited

    private void labellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellogoutMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labellogout.setBackground(clr);
    }//GEN-LAST:event_labellogoutMouseEntered

    private void labellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellogoutMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        labellogout.setBackground(clr);
    }//GEN-LAST:event_labellogoutMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         SimpleDateFormat Date_Format = new SimpleDateFormat("YYYY-MM-dd"); 
        String datefrom=  Date_Format.format(dateChooser_from.getDate());
      String dateto=  Date_Format.format(dateChooser_to.getDate());
       
        MessageFormat header=new MessageFormat("Report From "+datefrom+" To " +dateto);
        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {
            tbl_feesDetails.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        } catch (Exception e) {
            e.getMessage();
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         exportToExcel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearTable();
        setRecordsToTable();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        SimpleDateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
        String date = dateformat.format(new Date());
        
        try{
            File f = fileChooser.getSelectedFile();
            String path = f.getAbsolutePath();
            path = path+"_"+date+".xlsx";
            txt_filePath.setText(path);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filePathActionPerformed

    private void btn_home4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_home4MouseClicked
        // TODO add your handling code here:
         ViewAllRecords allrecords = new ViewAllRecords();
        allrecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_home4MouseClicked

    private void btn_home6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_home6MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_home6MouseClicked

    private void btn_home5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_home5MouseClicked
        // TODO add your handling code here:
         AddFees addfees = new AddFees();
        addfees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_home5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_courses;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_home3;
    private javax.swing.JLabel btn_home4;
    private javax.swing.JLabel btn_home5;
    private javax.swing.JLabel btn_home6;
    private javax.swing.JLabel btn_record;
    private javax.swing.JComboBox<String> combo_courseDetails;
    private com.toedter.calendar.JDateChooser dateChooser_from;
    private com.toedter.calendar.JDateChooser dateChooser_to;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelallrecord;
    private javax.swing.JPanel labelback;
    private javax.swing.JPanel labelcourses;
    private javax.swing.JPanel labelhome;
    private javax.swing.JPanel labellist;
    private javax.swing.JPanel labellogout;
    private javax.swing.JPanel labelrecord;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_totalAmount;
    private javax.swing.JLabel lbl_totalInWords;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JTable tbl_feesDetails;
    private javax.swing.JTextField txt_filePath;
    // End of variables declaration//GEN-END:variables
}
