/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;

/**
 *
 * @author kuson
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addfees = new javax.swing.JPanel();
        btn_addfees = new javax.swing.JLabel();
        searchrecord = new javax.swing.JPanel();
        btn_searchrecord = new javax.swing.JLabel();
        viewrecord = new javax.swing.JPanel();
        btn_viewrecord = new javax.swing.JLabel();
        editcourse = new javax.swing.JPanel();
        btn_editcourse = new javax.swing.JLabel();
        viewcourse = new javax.swing.JPanel();
        btn_viewcourse = new javax.swing.JLabel();
        viewreport = new javax.swing.JPanel();
        btn_viewreport = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        btn_about = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Affliated to R.G.P.V. Bhopal");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 200, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("  LAKSHMI NARIAN COLLEGE OF TECHNOLOGY & SCIENCE , Bhopal ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 1060, 60));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Approved by AICTE &Govt. of M.P.");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 250, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/lncts logo.jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addfees.setBackground(new java.awt.Color(0, 102, 102));
        addfees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfeesMouseClicked(evt);
            }
        });
        addfees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addfees.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_addfees.setForeground(new java.awt.Color(255, 255, 255));
        btn_addfees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/plus.png"))); // NOI18N
        btn_addfees.setText("  Add Fees");
        btn_addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addfeesMouseExited(evt);
            }
        });
        addfees.add(btn_addfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 140));

        jPanel1.add(addfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 310, 140));

        searchrecord.setBackground(new java.awt.Color(0, 102, 102));
        searchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        searchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_searchrecord.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_searchrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search-document.png"))); // NOI18N
        btn_searchrecord.setText("Search Record");
        btn_searchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchrecordMouseExited(evt);
            }
        });
        searchrecord.add(btn_searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 140));

        jPanel1.add(searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 310, 140));

        viewrecord.setBackground(new java.awt.Color(0, 102, 102));
        viewrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        viewrecord.setMinimumSize(new java.awt.Dimension(310, 140));
        viewrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewrecord.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_viewrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_viewrecord.setText(" View Record");
        btn_viewrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewrecordMouseExited(evt);
            }
        });
        viewrecord.add(btn_viewrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 140));

        jPanel1.add(viewrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 310, 140));

        editcourse.setBackground(new java.awt.Color(0, 102, 102));
        editcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        editcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_editcourse.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_editcourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_editcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit.png"))); // NOI18N
        btn_editcourse.setText("Edit Course");
        btn_editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseExited(evt);
            }
        });
        editcourse.add(btn_editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 140));

        jPanel1.add(editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, -1));

        viewcourse.setBackground(new java.awt.Color(0, 102, 102));
        viewcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        viewcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewcourse.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_viewcourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/text-book-opened-from-top-view.png"))); // NOI18N
        btn_viewcourse.setText(" View Courses");
        btn_viewcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewcourseMouseExited(evt);
            }
        });
        viewcourse.add(btn_viewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 140));

        jPanel1.add(viewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 310, 140));

        viewreport.setBackground(new java.awt.Color(0, 102, 102));
        viewreport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        viewreport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_viewreport.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_viewreport.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view report.png"))); // NOI18N
        btn_viewreport.setText(" View Report");
        btn_viewreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewreportMouseExited(evt);
            }
        });
        viewreport.add(btn_viewreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 140));

        jPanel1.add(viewreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 310, 140));

        logout.setBackground(new java.awt.Color(0, 102, 102));
        logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        logout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 80));

        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 170, 80));

        about.setBackground(new java.awt.Color(0, 102, 102));
        about.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_about.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/about.png"))); // NOI18N
        btn_about.setText("About");
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });
        about.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 80));

        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 520, 170, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1540, 680));

        setSize(new java.awt.Dimension(1554, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        addfees.setBackground(clr);
    }//GEN-LAST:event_btn_addfeesMouseEntered

    private void btn_addfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,102,102);
        addfees.setBackground(clr);
    }//GEN-LAST:event_btn_addfeesMouseExited

    private void btn_searchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        searchrecord.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseEntered

    private void btn_searchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        searchrecord.setBackground(clr);
    }//GEN-LAST:event_btn_searchrecordMouseExited

    private void btn_viewrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewrecordMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        viewrecord.setBackground(clr);
    }//GEN-LAST:event_btn_viewrecordMouseEntered

    private void btn_viewrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewrecordMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        viewrecord.setBackground(clr);
    }//GEN-LAST:event_btn_viewrecordMouseExited

    private void btn_editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        editcourse.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseEntered

    private void btn_editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        editcourse.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseExited

    private void btn_viewcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewcourseMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        viewcourse.setBackground(clr);
    }//GEN-LAST:event_btn_viewcourseMouseEntered

    private void btn_viewcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewcourseMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        viewcourse.setBackground(clr);
    }//GEN-LAST:event_btn_viewcourseMouseExited

    private void btn_viewreportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        viewreport.setBackground(clr);
    }//GEN-LAST:event_btn_viewreportMouseEntered

    private void btn_viewreportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        viewreport.setBackground(clr);
    }//GEN-LAST:event_btn_viewreportMouseExited

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        // TODO add your handling code here:
          Color clr  = new Color(0,51,51);
        about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        // TODO add your handling code here:
         Color clr  = new Color(0,102,102);
        about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseExited

    private void addfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeesMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_addfeesMouseClicked

    private void btn_addfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addfeesMouseClicked
        // TODO add your handling code here:
       AddFees addfees = new AddFees();
       addfees.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_addfeesMouseClicked

    private void btn_searchrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchrecordMouseClicked
        // TODO add your handling code here:
         SearchRecord search= new SearchRecord();
      search.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_searchrecordMouseClicked

    private void btn_editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseClicked
        // TODO add your handling code here:
        
        EditCourse edit = new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editcourseMouseClicked

    private void btn_viewrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewrecordMouseClicked
        // TODO add your handling code here:
        
        ViewAllRecords allrecords = new ViewAllRecords();
        allrecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_viewrecordMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        // TODO add your handling code here:
        CopyRight copyright = new CopyRight();
        copyright.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_aboutMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_viewreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewreportMouseClicked
        // TODO add your handling code here:
        GenerateReport report  = new GenerateReport();
        report.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_viewreportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about;
    private javax.swing.JPanel addfees;
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_addfees;
    private javax.swing.JLabel btn_editcourse;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_searchrecord;
    private javax.swing.JLabel btn_viewcourse;
    private javax.swing.JLabel btn_viewrecord;
    private javax.swing.JLabel btn_viewreport;
    private javax.swing.JPanel editcourse;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel searchrecord;
    private javax.swing.JPanel viewcourse;
    private javax.swing.JPanel viewrecord;
    private javax.swing.JPanel viewreport;
    // End of variables declaration//GEN-END:variables
}
