package fees_management_system;


//import .*;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kuson
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecord();
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    
    public void getRecord()
    {
        try{
//               Connection con = JDBConnection.getConnection();
               Class.forName("com.mysql.cj.jdbc.Driver");
           
                   Connection con =DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/fees_management","root","");
                   
               PreparedStatement pst = con.prepareStatement("Select * from fees_details order by reciept_no desc limit 1");
               ResultSet rs= pst.executeQuery();
//             rs.last();
                rs.next();
                
                txt_receiptNo.setText(rs.getString("reciept_no"));
                txt_paymentMode.setText(rs.getString("payment_mode"));
                
                String paymentMode = rs.getString("payment_mode");
                if(paymentMode.equalsIgnoreCase("cash"))
                {
                    lbl_cheque_dd.setText("Cheque No :-");
                    txt_cheque_dd.setText("-");
                    txt_bankName.setText("-");
                    
                }
                
                if(paymentMode.equalsIgnoreCase("cheque"))
                {
                    lbl_cheque_dd.setText("Cheque No :-");
                    txt_cheque_dd.setText(rs.getString("cheque_no"));
                    txt_bankName.setText(rs.getString("bank_name"));
                    
                }
                
                if(paymentMode.equalsIgnoreCase("dd"))
                {
                    lbl_cheque_dd.setText("DD No :-");
                    txt_cheque_dd.setText(rs.getString("dd_no"));
                    txt_bankName.setText(rs.getString("bank_name"));
                    
                }
                
                 if(paymentMode.equalsIgnoreCase("card"))
                {
                    lbl_cheque_dd.setText("Cheque _ DD :- ");
                    txt_cheque_dd.setText(rs.getString(" -"));
                    txt_bankName.setText(rs.getString("bank_name"));
                    
                }
                 
                 txt_receivedFrom.setText(rs.getString("student_name"));
                 txt_date.setText(rs.getString("date"));
                 txt_gstin.setText(rs.getString("gstin"));
                 txt_year1.setText(rs.getString("year1"));
                 txt_year2.setText(rs.getString("year2"));
                 
                 txt_initialAmount.setText(rs.getString("amount"));
                 txt_cgst.setText(rs.getString("cgst"));
                 txt_sgst.setText(rs.getString("sgst"));
                 txt_total1.setText(rs.getString("total_amount"));
                 txt_totalInWords.setText(rs.getString("total_in_words"));
                 txt_remark.setText(rs.getString("remark"));
                 txt_courseName1.setText(rs.getString("courses"));
                 
            }
        
        catch(Exception e)
        {
           e.printStackTrace();
        }
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        labelhome = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        labelrecord = new javax.swing.JPanel();
        btn_record = new javax.swing.JLabel();
        labelcourses = new javax.swing.JPanel();
        btn_courses = new javax.swing.JLabel();
        labellist = new javax.swing.JPanel();
        btn_home3 = new javax.swing.JLabel();
        labelallrecord = new javax.swing.JPanel();
        btn_home4 = new javax.swing.JLabel();
        labellogout = new javax.swing.JPanel();
        btn_home6 = new javax.swing.JLabel();
        labelprint1 = new javax.swing.JPanel();
        btn_homeprint = new javax.swing.JLabel();
        labeledit = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_receiptNo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_courseName1 = new javax.swing.JLabel();
        txt_totalInWords = new javax.swing.JLabel();
        sgst = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cgst1 = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JLabel();
        txt_total2 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_total4 = new javax.swing.JLabel();
        txt_total6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelhome.setBackground(new java.awt.Color(0, 102, 102));
        labelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelhomeMouseExited(evt);
            }
        });
        labelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btn_home.setText(" HOME");
        btn_home.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelhome.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 60));

        panelsidebar.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 70));

        labelrecord.setBackground(new java.awt.Color(0, 102, 102));
        labelrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelrecordMouseExited(evt);
            }
        });
        labelrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_record.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btn_record.setText("Search Record");
        btn_record.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelrecord.add(btn_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 70));

        panelsidebar.add(labelrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 70));

        labelcourses.setBackground(new java.awt.Color(0, 102, 102));
        labelcourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelcourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelcoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelcoursesMouseExited(evt);
            }
        });
        labelcourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_courses.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_courses.setForeground(new java.awt.Color(255, 255, 255));
        btn_courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_courses.setText(" Edit Courses");
        btn_courses.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coursesMouseClicked(evt);
            }
        });
        labelcourses.add(btn_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, -1));

        panelsidebar.add(labelcourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 70));

        labellist.setBackground(new java.awt.Color(0, 102, 102));
        labellist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labellist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labellistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labellistMouseExited(evt);
            }
        });
        labellist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home3.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home3.setForeground(new java.awt.Color(255, 255, 255));
        btn_home3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btn_home3.setText(" Course List");
        btn_home3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labellist.add(btn_home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 60));

        panelsidebar.add(labellist, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 70));

        labelallrecord.setBackground(new java.awt.Color(0, 102, 102));
        labelallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelallrecordMouseExited(evt);
            }
        });
        labelallrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home4.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home4.setForeground(new java.awt.Color(255, 255, 255));
        btn_home4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_home4.setText("View All Record");
        btn_home4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home4MouseClicked(evt);
            }
        });
        labelallrecord.add(btn_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelsidebar.add(labelallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 300, 70));

        labellogout.setBackground(new java.awt.Color(0, 102, 102));
        labellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labellogoutMouseExited(evt);
            }
        });
        labellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home6.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_home6.setForeground(new java.awt.Color(255, 255, 255));
        btn_home6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_home6.setText(" Logout");
        btn_home6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_home6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home6MouseClicked(evt);
            }
        });
        labellogout.add(btn_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        panelsidebar.add(labellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 300, 70));

        labelprint1.setBackground(new java.awt.Color(0, 102, 102));
        labelprint1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labelprint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelprint1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelprint1MouseExited(evt);
            }
        });
        labelprint1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_homeprint.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_homeprint.setForeground(new java.awt.Color(255, 255, 255));
        btn_homeprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btn_homeprint.setText("Print");
        btn_homeprint.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_homeprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeprintMouseClicked(evt);
            }
        });
        labelprint1.add(btn_homeprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        panelsidebar.add(labelprint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 300, 70));

        labeledit.setBackground(new java.awt.Color(0, 102, 102));
        labeledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        labeledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeleditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeleditMouseExited(evt);
            }
        });
        labeledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        labeledit.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        panelsidebar.add(labeledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 300, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 810));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("LAKSHMI NARIAN COLLEGE OF TECHNOLOGY & SCIENCE , Bhopal ");
        panel_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/lncts logo.jpg"))); // NOI18N
        panel_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 120, 120));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Approved by AICTE &Govt. of M.P.");
        panel_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 250, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Affliated to R.G.P.V. Bhopal");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 200, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Raisen Road , near Hanuman Mandir , Kalchuri Nagar , Bhopal , Madhya Pradesh 462022");
        panel_print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 570, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 890, 4));

        txt_receiptNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_receiptNo.setForeground(new java.awt.Color(0, 0, 51));
        txt_receiptNo.setText("Receipt no :");
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("The following payment in the college office for the year :-");
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 410, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Receipt no :-         COT-");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Payment Mode :-");
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, -1));

        txt_paymentMode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_paymentMode.setForeground(new java.awt.Color(0, 0, 51));
        txt_paymentMode.setText("Payment Mode :-");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 150, -1));

        lbl_cheque_dd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_cheque_dd.setText("Cheque _ DD :- ");
        panel_print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, -1));

        txt_cheque_dd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_cheque_dd.setForeground(new java.awt.Color(0, 0, 51));
        txt_cheque_dd.setText("Cheque _ DD :- ");
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 150, -1));

        txt_receivedFrom.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_receivedFrom.setForeground(new java.awt.Color(0, 0, 51));
        txt_receivedFrom.setText("Received From :-");
        panel_print.add(txt_receivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("-");
        panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 20, -1));

        txt_gstin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(0, 0, 51));
        txt_gstin.setText("GSTIN :-");
        panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 130, -1));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(0, 0, 51));
        txt_year1.setText("2021");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 50, -1));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(0, 0, 51));
        txt_year2.setText(" 2022 ");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 60, -1));

        lbl_bankName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_bankName.setText("Bank Name :-");
        panel_print.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 150, -1));

        txt_bankName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_bankName.setForeground(new java.awt.Color(0, 0, 51));
        txt_bankName.setText("Bank Name :-");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 150, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Received From :-");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 150, -1));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_date.setForeground(new java.awt.Color(0, 0, 51));
        txt_date.setText("Date :-");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 120, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("GSTIN :-");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 100, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Date :-");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 100, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 910, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 910, 10));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Amount(Rs.)");
        panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 130, 30));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_sgst.setText("sgst");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 60, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Head");
        panel_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 60, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("S.No.");
        panel_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 60, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("1");
        panel_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 60, 30));

        txt_courseName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_courseName1.setText("1");
        panel_print.add(txt_courseName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 60, 30));

        txt_totalInWords.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_totalInWords.setForeground(new java.awt.Color(0, 0, 51));
        txt_totalInWords.setText("total");
        panel_print.add(txt_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 370, 30));

        sgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgst.setText("sgst (9%)");
        panel_print.add(sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 80, 30));

        txt_initialAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_initialAmount.setText("sgst");
        panel_print.add(txt_initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 60, 30));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_cgst.setText("sgst");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 60, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 290, 10));

        cgst1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cgst1.setText("cgst (9%)");
        panel_print.add(cgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 80, 30));

        txt_total1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_total1.setForeground(new java.awt.Color(0, 0, 51));
        txt_total1.setText("total");
        panel_print.add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 80, 30));

        txt_total2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_total2.setText("Receiver Signature :-");
        panel_print.add(txt_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, 210, 30));

        txt_remark.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_remark.setForeground(new java.awt.Color(0, 0, 51));
        txt_remark.setText("Remark :-");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 280, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 290, 10));

        txt_total4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_total4.setText("total in words :-");
        panel_print.add(txt_total4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 140, 30));

        txt_total6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_total6.setText("Remark :-");
        panel_print.add(txt_total6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 140, 30));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 1030, 780));

        setSize(new java.awt.Dimension(1554, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseEntered
        // TODO add your handling code here:
         Color clr  = new Color(0,51,51);
        labelhome.setBackground(clr);
     
    }//GEN-LAST:event_labelhomeMouseEntered

    private void labelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labelhome.setBackground(clr);
     
    }//GEN-LAST:event_labelhomeMouseExited

    private void labelrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelrecordMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelrecord.setBackground(clr);
    }//GEN-LAST:event_labelrecordMouseEntered

    private void labelrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelrecordMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labelrecord.setBackground(clr);
    }//GEN-LAST:event_labelrecordMouseExited

    private void labelcoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcoursesMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelcourses.setBackground(clr);
    }//GEN-LAST:event_labelcoursesMouseEntered

    private void labelcoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcoursesMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labelcourses.setBackground(clr);
    }//GEN-LAST:event_labelcoursesMouseExited

    private void labellistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellistMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labellist.setBackground(clr);
    }//GEN-LAST:event_labellistMouseEntered

    private void labellistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellistMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labellist.setBackground(clr);
    }//GEN-LAST:event_labellistMouseExited

    private void labelallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelallrecordMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labelallrecord.setBackground(clr);
    }//GEN-LAST:event_labelallrecordMouseEntered

    private void labelallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelallrecordMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labelallrecord.setBackground(clr);
    }//GEN-LAST:event_labelallrecordMouseExited

    private void labellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellogoutMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labellogout.setBackground(clr);
    }//GEN-LAST:event_labellogoutMouseEntered

    private void labellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labellogoutMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labellogout.setBackground(clr);
    }//GEN-LAST:event_labellogoutMouseExited

    private void labelprint1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelprint1MouseEntered
        // TODO add your handling code her
        Color clr  = new Color(0,51,51);
        labelprint1.setBackground(clr);
    }//GEN-LAST:event_labelprint1MouseEntered

    private void labelprint1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelprint1MouseExited
        // TODO add your handling code her
          Color clr  = new Color(0,102,102);
        labelprint1.setBackground(clr);
    }//GEN-LAST:event_labelprint1MouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
//        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_editMouseExited

    private void labeleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeleditMouseEntered
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        labeledit.setBackground(clr);
     
    }//GEN-LAST:event_labeleditMouseEntered

    private void labeleditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeleditMouseExited
        // TODO add your handling code here:
          Color clr  = new Color(0,102,102);
        labeledit.setBackground(clr);
        
    }//GEN-LAST:event_labeleditMouseExited

    private void btn_homeprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeprintMouseClicked
        // TODO add your handling code here:
        
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(.60,.75);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
        
    }//GEN-LAST:event_btn_homeprintMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_home4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_home4MouseClicked
        // TODO add your handling code here:
         ViewAllRecords allrecords = new ViewAllRecords();
        allrecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_home4MouseClicked

    private void btn_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coursesMouseClicked
        // TODO add your handling code here:
          EditCourse edit = new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_coursesMouseClicked

    private void btn_home6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_home6MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_home6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_courses;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_home3;
    private javax.swing.JLabel btn_home4;
    private javax.swing.JLabel btn_home6;
    private javax.swing.JLabel btn_homeprint;
    private javax.swing.JLabel btn_record;
    private javax.swing.JLabel cgst1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel labelallrecord;
    private javax.swing.JPanel labelcourses;
    private javax.swing.JPanel labeledit;
    private javax.swing.JPanel labelhome;
    private javax.swing.JPanel labellist;
    private javax.swing.JPanel labellogout;
    private javax.swing.JPanel labelprint1;
    private javax.swing.JPanel labelrecord;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JLabel sgst;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName1;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_receivedFrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total1;
    private javax.swing.JLabel txt_total2;
    private javax.swing.JLabel txt_total4;
    private javax.swing.JLabel txt_total6;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
